name: Launch on Tower

# Manually trigger the action with a button in GitHub
# Alternatively, trigger on release / push etc.
on:
  workflow_dispatch:

jobs:
  run-tower:
    name: Launch on Nextflow Tower
    # Don't run on forked repos
    if: github.repository == 'ewels/nf-core-testpipeline'
    runs-on: ubuntu-latest
    steps:
      - uses: ewels/tower-action@master
        # Use repository secrets for sensitive fields
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          bearer_token: ${{ secrets.TOWER_BEARER_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          pipeline: ${{ github.repository }}
          revision: ${{ github.sha }}
          workdir: ${{ secrets.AWS_S3_BUCKET }}/work/${{ github.sha }}
          # Set any custom pipeline params here - JSON object as single-line string
          parameters: '{ \"outdir\": \"${{ secrets.AWS_S3_BUCKET }}/results/${{ github.sha }}\" }'
          # List of config profiles to use - JSON list as single-line string
          profiles: '[ "test", "aws_tower" ]'
